name: AskAI
version: "${version}"
main: com.askai.AskAI
description: "${description}"
api-version: "1.20.6"

permissions:
  askai.use:
    description: "Send messages to AI providers with /chat"
    default: true
  askai.setkey:
    description: "Manage API keys with /chat setkey"
    default: true
  askai.admin:
    description: "Manage server-wide API keys in server-key mode"
    default: op
